# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\goods\add\goods_goodscode.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login.login_success_test import TestCaseLoginSuccess as LoginSuccess


class TestCaseGoodsGoodscode(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "goodsname-goodscode-code-msg": [
                    ["yoyo123", "", 2000, "缺少必填项goodscode"],
                    ["yoyo123", "yoyo123", 3003, "参数不合法"],
                    ["yoyo123", "yoyo123xx", 3003, "参数不合法"],
                    ["yoyo123", "sp_10086", 4000, "goodscode不能重复添加"],
                    ["yoyo123", "sp1aaaaaaaaabbbbbbbbbxxxxxxxxq", 3003, "参数不合法"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("新增商品接口-新增成功")
        .variables(
            **{
                "goodsname": "zxj01",
                "goodscode": "${goods_code()}",
                "merchantid": "100222",
                "merchantname": "商品的名称测试使用",
                "goodsprice": 90.9,
                "stock": 2000,
                "goodsgroupid": 2,
                "price": 20,
                "goodsstatus": 1,
            }
        )
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(RunTestCase("登录账号").call(LoginSuccess).export(*["token"])),
        Step(
            RunRequest("新增商品")
            .post("/api/v2/goods")
            .with_headers(**{"Authorization": "Token $token"})
            .with_json(
                {
                    "goodsname": "$goodsname",
                    "goodscode": "$goodscode",
                    "merchantid": "$merchantid",
                    "merchantname": "$merchantname",
                    "goodsprice": "$goodsprice",
                    "stock": "$stock",
                    "goodsgroupid": "$goodsgroupid",
                    "price": "$price",
                    "goodsstatus": "$goodsstatus",
                }
            )
            .validate()
            .assert_equal("body.code", "$code")
            .assert_equal("body.msg", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseGoodsGoodscode().test_start()
