# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\regsiter\register_success.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRegisterSuccess(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {"user-psw-email": [["${register_user()}", "123456", "108888778@qq.com"]]}
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("注册一个没有注册过的用户，注册成功").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("step-注册")
            .post("/api/v1/register")
            .with_json({"username": "$user", "password": "$psw", "email": ""})
            .validate()
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "register success!")
        ),
    ]


if __name__ == "__main__":
    TestCaseRegisterSuccess().test_start()
