# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\regsiter\regsiter_fail.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRegsiterFail(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "user-psw-email": [
                    ["tt", "123456", "108888778@qq.com"],
                    [
                        "tt11111111111111111111111111111111111111111111111111111111",
                        "123456",
                        "108888778@qq.com",
                    ],
                    ["${register_user()}", "123456", "12345"],
                    [" ", "123456", "108888778@qq.com"],
                    ["${register_user()}", " ", "108888778@qq.com"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("注册一个没有注册过的用户，注册成功").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("step-注册")
            .post("/api/v1/register")
            .with_json({"username": "$user", "password": "$psw", "email": ""})
            .validate()
            .assert_equal("body.code", 3003)
            .assert_equal("body.msg", "参数不合法")
        ),
    ]


if __name__ == "__main__":
    TestCaseRegsiterFail().test_start()
