# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\regsiter\regsiter_exsit_user.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRegsiterExsitUser(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters({"user-psw-email": [["zxjzxj03", "123456", "108888778@qq.com"]]}),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("注册重复用户").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("先注册新用户")
            .post("/api/v1/register")
            .with_json({"username": "$user", "password": "$psw", "email": ""})
            .validate()
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "register success!")
        ),
        Step(
            RunRequest("用户已被注册")
            .post("/api/v1/register")
            .with_json({"username": "$user", "password": "$psw", "email": ""})
            .validate()
            .assert_equal("body.code", 2000)
            .assert_equal("body.msg", "zxjzxj03用户已被注册")
        ),
    ]


if __name__ == "__main__":
    TestCaseRegsiterExsitUser().test_start()
