# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login\login_urlencoded.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginUrlencoded(HttpRunner):

    config = (
        Config("登录接口-输入正确账号密码,登录成功")
        .variables(**{"user": "${ENV(user)}", "psw": "${ENV(psw)}"})
        .base_url("${ENV(base_url)}")
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("登录成功")
            .post("/api/v4/login")
            .with_data({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.code", 0)
            .assert_equal("body.username", "$user")
            .assert_length_equal("body.token", 40)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginUrlencoded().test_start()
