# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\login\login_fail_01.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginFail01(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "user-psw-email": [
                    ["tt", "123456", ""],
                    ["", "123456", ""],
                    ["test", "123455", "1672728@qq.com"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("登录接口-输入错误的账号密码,返回正确")
        .variables(**{"user": "${ENV(user)}", "psw": "${ENV(psw)}"})
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(
            RunRequest("登录失败,提示正确")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw", "email": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 3003)
            .assert_length_equal("body.token", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginFail01().test_start()
