# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login\sign_csv.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseSignCsv(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"user-psw-code-msg-len_token": "${P(data/sign.csv)}"})
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("登录接口-sign登录")
        .variables(
            **{
                "user": "${ENV(user)}",
                "psw": "${ENV(psw)}",
                "code": 0,
                "msg": "login success!",
                "len_token": 40,
            }
        )
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(
            RunRequest("sign登录成功")
            .setup_hook("${setup_request($request)}")
            .post("/api/v3/login")
            .with_json({"username": "$user", "password": "$psw", "sign": "x"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "$msg")
            .assert_equal("body.code", "${str_to_int($code)}")
            .assert_length_equal("body.token", "${str_to_int($len_token)}")
        ),
    ]


if __name__ == "__main__":
    TestCaseSignCsv().test_start()
